USE `essentialmode`;

CREATE TABLE IF NOT EXISTS `flayers` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `img` VARCHAR(255) NOT NULL,
  `x` DECIMAL(10,5) NOT NULL,
  `y` DECIMAL(10,5) NOT NULL,
  `z` DECIMAL(10,5) NOT NULL,
  `cid` MEDIUMINT UNSIGNED NOT NULL,
  `expire` INT UNSIGNED NOT NULL,
  `region` VARCHAR(255) NOT NULL
)
